### ISSUE TITLE
Usage Instructions

### ISSUE THREAD

**Issue by pjpalomaki** [tirish/steam-shortcut-editor#1]
Hi,

Sorry, I'm a total noob to NPM and node.js.. I really want to manually edit the Steam shortcuts.vdf and this program looks like it could do that ... If I understood at all how to use it.

I'm on Win 7 and I downloaded the package .. How do I actually use this? Or am I supposed to run it in Chrome? And where do I define the actual shortcut details (i.e. "AppName", "exe"  etc..)

I would really appreciate some info on the concepts of how all this works and even better, step-by-step instructions how to update the shortcuts.vdf..

Thanks,
PJ

**Comment by pjpalomaki** [comment]
This is what I got when running npm i steam-shortcut-editor-master:

C:\Apps>npm i steam-shortcut-editor-master
C:\Apps
└─┬ steam-shortcut-editor@1.0.2
  └── lodash@3.10.1

npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Apps\package.json'
npm WARN EPACKAGEJSON Apps No description
npm WARN EPACKAGEJSON Apps No repository field.
npm WARN EPACKAGEJSON Apps No README data
npm WARN EPACKAGEJSON Apps No license field.

**Comment by tirish** [comment]
@pjpalomaki this repo is a Node.js library. In order to use it you must write a Node app to utilize it. This can be done with a few commands and a simple javascript file.
1. Install Node.js & NPM
2. Create an empty directory somewhere on your computer
3. Create a javascript file in that new directory, something like `app.js`
4. In that directory (using terminal/command-prompt) run `npm init`, following the prompts to create a `package.json` file
5. In that directory (using terminal/command-prompt) run `npm i steam-shortcut-editor --save`
6. Add content to `app.js` to look something like [the sample in the README](https://github.com/tirish/steam-shortcut-editor#usage)
   - The sample will read the file and write it to the same location with a different name, just to show it works
7. You will need to tailor `app.js` to your needs. May want to consider maintaining a standalone `json` file that follows the format [from the README](https://github.com/tirish/steam-shortcut-editor#data-contract---shortcut-object) and then have your `app.js` convert that `json` file into a `shortcuts.vdf` file.

Hopefully this helps. If you need more help just let me know.

**Comment by tirish** [comment]
Closing issue. Let me know if you need anymore help.

**Comment by Arrow-Loop** [comment]
Hello, I attempted to follow these instructions and I think I am stuck at step 6 from above. I don't know where to go from here. I am trying to view my existing Steam Shortcuts vdf file and made one minor change to the existing shortcut data and can't seem to get any further. The README instructions are confusing me. Any help would be appreciated.

Thanks

**Comment by tirish** [comment]
@coasternd can you provide your code?

You can also use the [sample.js](https://github.com/tirish/steam-shortcut-editor/blob/master/sample.js) as a starting point.

**Comment by Arrow-Loop** [comment]
Here is what is in my app.js

```javascript
var shortcut = require('steam-shortcut-editor');

var filePath = '52031986/config/shortcuts.vdf';
var writePath = filePath.replace('shortcuts','shortcuts_write');

shortcut.parseFile(filePath,
    { autoConvertArrays: true, autoConvertBooleans: true, dateProperties: ['LastPlayTime']},
function(err, obj, inputBuffer){

    if(err){
        console.log('failed to read '+filePath);
        return;
    }

    //Buffer read from file
    console.log('Raw Buffer:', inputBuffer);

    //Parsed Object
    console.log(JSON.stringify(obj,null,2));

    shortcut.writeFile(writePath, obj, function (err) {
        if(err){
            console.log('failed to write '+writePath);
        }
    });

});
```

I pulled this from your NPM webpage. I don't think it's right though it looks nothing like your Sample.js. Once I've updated it to look like your Sample, how do I execute the app? I am trying to see what my Shortcuts file before I go changing anything. Some sort of demo video on how to get this setup would be helpful.

Thanks,

**Comment by tirish** [comment]
@coasternd the file path needs to be absolute, so something like `C:/Program Files (x86)/Steam/<steamId>/config/shortcuts.vdf`

If you just want to see the contents, omit the `shortcut.writefile` code.
