### ISSUE TITLE
TypeError: Cannot set property 'exe' of undefined

### ISSUE THREAD

**Issue by Pienkaito** [tirish/steam-shortcut-editor#3]
I had issues running this.
At first I got an Error: Cannot find module 'lodash', but I could fix that by installing it.

After that I get this.
TypeError: Cannot set property 'exe' of undefined
    at Object.module.exports [as parse](C:Newlibparser.js:47:22)
    at C:\New\sample.js:16:28
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:380:3)

**Comment by tirish** [comment]
@Pienkaito are you running the `sample.js` in this repo? 

If so, did you set the `STEAM_USER_ID` environment variable to your User Id? This is [used to determine the path to your `shortcuts.vdf` file](https://github.com/tirish/steam-shortcut-editor/blob/master/sample.js#L6). You can just change that line to the path if you are having trouble with the environment variables.

Assuming that the `shortcut.vdf` file path is correct and the file is actually being read, it looks like there might be an unsupported format present in your `shortcut.vdf` file (since it is not hitting the `AppName` keyword first). Could you send me a gist of your `shortcut.vdf` file?

**Comment by xotmatrix** [comment]
I'm having the same problem. It's parsing the file (or trying to) but some sections in my shortcuts.vdf have altered case or are not parsed. I tried to make it work but I'm new to node.js and don't completely follow everything. I've uploaded a binary gist of my file.

https://gist.github.com/xotmatrix/e70f2e0c9e6dafefc3754fdc0515240f

**Comment by tirish** [comment]
@xotmatrix what OS are you using? I'll see if I can figure out the issue

**Comment by xotmatrix** [comment]
I'm using Windows 10.

**Comment by tirish** [comment]
@xotmatrix looks like the issue was that all of the keywords in your `shortcuts.vdf` file were lower case, but the parsing code was case sensitive. I have addressed this [in this commit](https://github.com/tirish/steam-shortcut-editor/commit/7875cac943619578976b841ac76fe61f8e41a11c) and updated the NPM package to version 1.1.0

Let me know if you have any other issues

**Comment by xotmatrix** [comment]
OK, sample.js is now able to execute to completion but the parser is not handling or recognizing the properties correctly. Several properties are ignored and lost. The "hidden" property is not being parsed or written correctly. The sanity check log is miles long. Sanity check fails even for .vdf files writer.js produces.

I've updated my gist with original and generated .vdf files as well as console logs (sanity1.txt is the log for the initial run, sanity2.txt is the log after running sample.js on the generated .vdf)

https://gist.github.com/xotmatrix/e70f2e0c9e6dafefc3754fdc0515240f

I feel like I could be a good FOSS citizen and fix some of these problems myself but without a shortcuts.vdf specification, I'm at a bit of a loss. My motivation for getting this working is pretty low since I've lost the desire to populate shortcuts.vdf in a way that is unsupported by the Steam UI (chiefly, multiple shortcuts pointing to the same executable).

**Comment by tirish** [comment]
@xotmatrix I fear the file format may have changed from when this was originally implemented. The changes may warrant a rewrite of this library but I have not had the free time to dig in on these changes. I will try and find some time within the next week to take a closer look and hopefully push a fix. 

A note on the sanity check list: It does not properly handle case insensitivity, so there are several false negatives being thrown. However, there are indeed true mismatches, likely related to a change in format. It appears that extra characters are present in the original that ends up throwing off the rest of the matching.

**Comment by tirish** [comment]
Hey @xotmatrix, sorry I haven't gotten to this sooner. Looks like the schema has changed since my code was originally implemented. 

I took a look at my own `shortcuts.vdf` file, wrote a Node script to read it and print it to console (to show the escaped characters). I then took a crack at making sense of it, adding whitespace to improve readability and ultimately came up with this:
```

\u0000shortcuts\u0000
    \u0000
        0
        \u0000
            \u0001AppName\u0000Minecraft - FTB\u0000
            \u0001exe\u0000"U:\\Users\\Tommy\\Minecraft\\Feed the Beast\\launcher^FTB_Launcher.exe"\u0000
            \u0001StartDir\u0000"U:\\Users\\Tommy\\Minecraft\\Feed the Beast\\"\u0000
            \u0001icon\u0000\u0000
            \u0001ShortcutPath\u0000\u0000
            \u0002IsHidden\u0000 \u0000\u0000\u0000 \u0000
            \u0002AllowDesktopConfig\u0000 \u0001\u0000\u0000 \u0000
            \u0002OpenVR\u0000 \u0000\u0000\u0000 \u0000
            \u0000tags\u0000
                \u0001
                    0
                    \u0000favorite\u0000
            \b
        \b
    \u0000
        1
        \u0000
            \u0001AppName\u0000Minecraft\u0000
            \u0001exe\u0000"U:\\Users\\Tommy\\Minecraft\\Vanilla\\Minecraft_New.exe"\u0000
            \u0001StartDir\u0000"U:\\Users\\Tommy\\Minecraft\\Vanilla\\"\u0000
            \u0001icon\u0000\u0000
            \u0001ShortcutPath\u0000\u0000
            \u0002IsHidden\u0000 \u0000\u0000\u0000 \u0000
            \u0002AllowDesktopConfig\u0000 \u0001\u0000\u0000 \u0000
            \u0002OpenVR\u0000 \u0000\u0000\u0000 \u0000
            \u0000tags\u0000
                \u0001
                    0
                    \u0000favorite\u0000
            \b
        \b
    \u0000
        2
        \u0000
            \u0001AppName\u0000Tom Clancy\'s The Division\u0000
            \u0001exe\u0000"C:\\Program Files (x86)\\Ubisoft\\Ubisoft Game Launcher\\games\\Tom Clancy\'s The Division\\TheDivision.exe"\u0000
            \u0001StartDir\u0000"C:\\Program Files (x86)\\Ubisoft\\Ubisoft Game Launcher\\games\\Tom Clancy\'s The Division\\"\u0000
            \u0001icon\u0000\u0000
            \u0001ShortcutPath\u0000\u0000
            \u0002IsHidden\u0000 \u0000\u0000\u0000 \u0000
            \u0002AllowDesktopConfig\u0000 \u0001\u0000\u0000 \u0000
            \u0002OpenVR\u0000 \u0000\u0000\u0000 \u0000
            \u0000tags\u0000
                \u0001
                    0
                    \u0000favorite\u0000
            \b
        \b
    \b
\b
```

So it appears there is a method to the madness.

Properties appear to follow the format: `<prefix><propertyName><value stuff>` The `<prefix>` seems to indicate the value data type:
- `\0000`: Array/Object
- `\0001`: String
- `\0002`: Boolean

The `<value stuff>` varies by data type.
- `String`: `\0000<content>\0000`
- `Boolean`: `\0000<bool sequence>\0000`. With the following sequences being the boolean values:
  - `True`: `\0000\0001\0000`
  - `False`: `\0000\0000\0000`
- `Array` or `Object`: `\0000<content>\b`
  - The `<array content>` uses the following repeating pattern for each element: `<type identifier><index><value>`
  - The `<type identifier>` is `\0000` for `String` array values and `\0001` for `Object` array values
  - The `<value>` is `\0000<content>\0000` for `String` array values and `\0000` followed by properties (defined above) for `Object` values

With all that, can probably write a proper parser that doesn't make any keyword assumptions.

**Comment by xotmatrix** [comment]
Nice work!

**Comment by tirish** [comment]
@xotmatrix this PR should address your issue: https://github.com/tirish/steam-shortcut-editor/pull/4

Note there are slight breaking changes, as it has no assumptions and therefore will not extract the `shortcuts` value for you. The result will look like `{ shortcuts: [...] }` and that same object should be written to the file.

Going to merge it soon and up the NPM version to 2.0.0

**Comment by tirish** [comment]
@xotmatrix give V2 a try. Closing this issue for now, can re-open if problems persist.
